### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'key3.pem'

### ISSUE THREAD

**Issue by synctext** [michael-the1/tsukiji#13]
```
Creating peer and sending messages.
 Started peer8
Attempting to start thread for peer9
Creating peer and sending messages.
 Started peer9
Attempting to start thread for peer10
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "simu.py", line 37, in start_peer
    create_peer(str(index), message[4], message[5], message[0])
  File "/home/pouwelse/GITHUB/decentral_market_BEP/tsukiji/udpsend.py", line 51, in create_peer
    reactor.listenMulticast(8005, senderObj, listenMultiple=True)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 387, in listenMulticast
    p.startListening()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 176, in startListening
    self._connectToProtocol()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 214, in _connectToProtocol
    self.protocol.makeConnection(self)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/protocol.py", line 711, in makeConnection
    self.doStart()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/protocol.py", line 675, in doStart
    self.startProtocol()
  File "/home/pouwelse/GITHUB/decentral_market_BEP/tsukiji/udpsend.py", line 22, in startProtocol
    self.send_message()
  File "/home/pouwelse/GITHUB/decentral_market_BEP/tsukiji/udpsend.py", line 42, in send_message
    msg = create_bid(self.price, self.qty, timeout=next_year)
  File "/home/pouwelse/GITHUB/decentral_market_BEP/tsukiji/orderbook.py", line 27, in create_bid
    'timeout': timeout
  File "/home/pouwelse/GITHUB/decentral_market_BEP/tsukiji/orderbook.py", line 88, in create_msg
    "id": get_public_bytestring(),
  File "/home/pouwelse/GITHUB/decentral_market_BEP/tsukiji/crypto.py", line 39, in get_public_bytestring
    key = retrieve_key()
  File "/home/pouwelse/GITHUB/decentral_market_BEP/tsukiji/crypto.py", line 33, in retrieve_key
    with open("key"+str(n)+".pem", 'r') as f:
IOError: [Errno 2] No such file or directory: 'key3.pem'
```

**Comment by Yuugoh** [comment]
Keyfiles are now checked for existance and created if missing when simu.py is run.
